PREFIX dct: <http://purl.org/dc/terms/>
PREFIX zbwext: <http://zbw.eu/namespaces/zbw-extensions/>

# count filmsections, aggregated by source

select (str(count(?section)) as ?sectionCount) ?source
where {
  graph <http://zbw.eu/beta/film/ng> {
    ?section a zbwext:Pm20FilmItem;
    dct:source ?source .
  }
}
group by ?source

